### ISSUE TITLE
App Random Restart

### ISSUE THREAD

**Issue by MSFTserver** [pirl/Oystr#2]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.1`
OS & Version: windows
Node version: `pirl 0.0.0` ¯\_(ツ)_/¯
Number of blocks synchronized: 122433
```
wallet closes and reopens randomly, left the wallet open for about 30 mins now already restarted at least 3 times

**Comment by Woofard** [comment]
Came to say the exact same thing! Just downloaded, synced and about 30 minutes later - wallet performed a random blink off and restarted.

**Comment by chr1sn0** [comment]
we are working on a version based on the actual Mist. This bug will be fixed there.
