### ISSUE TITLE
Lost coins

### ISSUE THREAD

**Issue by jernest93** [pirl/Oystr#3]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

Can anyone help me out here?
First I have tried to create a wallet contract but it never was successful.
Second I already mined like 35 PIRL credited into my main wallet, I sent it to my exchange wallet and it has been more than four hour and I got 0 confirmation of 12. I was using PirlOystrLite Version 0.0.1 but doing some research I find out that it was a new version nautilus, so I decided to backup my account and imported into the new version and now I got 0 coins and no transaction
![image](https://user-images.githubusercontent.com/35437610/34926995-2bb887b2-f981-11e7-9410-1daf06ca4506.png)
![image](https://user-images.githubusercontent.com/35437610/34927006-38bd1838-f981-11e7-8a39-2417cd674a4b.png)
![image](https://user-images.githubusercontent.com/35437610/34927029-56aaaab8-f981-11e7-914f-34b10789ab9f.png)

```
Version: `0.0.1`
OS & Version: windows/linux/osx
Node version: `pirl 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by chr1sn0** [comment]
Hi,
Oyster never showed confirmations. This is fixed in Nautilus Wallet.
I think the transaction to your exchange(cryptopia ?) was made. Cryptopia is slow atm. It can take hours to deposit on their wallets.
If u want, join on our discord and write me a direct message.
Greetz

**Comment by antonvtimin** [comment]
Hi!
I have the same issue. Yesterday I've sent almost the same :-D amount of PIRL to Cryptopia account, already 23 hours since that. There is no confirmations (ok, I have understood that Oystr does'n show them) and NO COINS on my Cryptopia account ((( Can you help me with that?

**Comment by chr1sn0** [comment]
Hi,
ask Cryptopia for help. If the TX is in the blockchain, the coins are in cryptopias wallet. 

Greetz
